# Generated by Django 6.0.3 on 2026-04-19 21:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('schema', models.JSONField(default=dict)),
                ('estimated_duration_ms', models.IntegerField()),
                ('default_budget_sats', models.BigIntegerField()),
                ('required_capabilities', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('is_microtask', models.BooleanField(default=False)),
                ('required_capabilities', models.JSONField(default=list)),
                ('required_human', models.BooleanField(default=False)),
                ('required_trust_level', models.IntegerField(default=1)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('budget_sats', models.BigIntegerField()),
                ('min_bid_sats', models.BigIntegerField(blank=True, null=True)),
                ('max_bid_sats', models.BigIntegerField(blank=True, null=True)),
                ('assigned_price_sats', models.BigIntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('executing', 'Executing'), ('verifying', 'Verifying'), ('completed', 'Completed'), ('failed', 'Failed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('execution_log', models.JSONField(default=list)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('verification_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('matched_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MicroTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('order', models.IntegerField()),
                ('budget_sats', models.BigIntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
                ('parent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microtasks', to='tasks.task')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
