# Generated by Django 6.0.3 on 2026-04-19 21:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('rule_type', models.CharField(max_length=50)),
                ('conditions', models.JSONField(default=dict)),
                ('actions', models.JSONField(default=dict)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngineMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric_name', models.CharField(choices=[('accuracy', 'Accuracy'), ('latency', 'Latency'), ('throughput', 'Throughput'), ('cost_efficiency', 'Cost Efficiency')], max_length=50)),
                ('current_value', models.FloatField()),
                ('average_value', models.FloatField()),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('value_history_json', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('metric_name',)},
            },
        ),
        migrations.CreateModel(
            name='EngineDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision_type', models.CharField(choices=[('routing', 'Routing Decision'), ('pricing', 'Pricing Decision'), ('risk', 'Risk Assessment'), ('policy', 'Policy Enforcement')], max_length=20)),
                ('selected_agent_type', models.CharField(blank=True, max_length=10, null=True)),
                ('price_sats', models.BigIntegerField(blank=True, null=True)),
                ('confidence_score', models.FloatField()),
                ('risk_score', models.FloatField()),
                ('fraud_probability', models.FloatField()),
                ('reasoning', models.TextField()),
                ('decision_log_json', models.JSONField(default=dict)),
                ('price_breakdown_json', models.JSONField(default=dict)),
                ('decision_time', models.DateTimeField(auto_now_add=True)),
                ('latency_ms', models.IntegerField()),
                ('selected_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'ordering': ['-decision_time'],
                'indexes': [models.Index(fields=['decision_type', '-decision_time'], name='core_engine_decisio_afe09d_idx'), models.Index(fields=['task', 'decision_type'], name='core_engine_task_id_aa9378_idx')],
            },
        ),
    ]
