# Generated by Django 6.0.3 on 2026-04-19 21:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DispatchRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_agents', models.JSONField(default=list)),
                ('decision_reason', models.TextField()),
                ('score', models.FloatField()),
                ('dispatch_latency_ms', models.IntegerField()),
                ('selected_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=10)),
                ('queue_position', models.IntegerField()),
                ('enqueued_at', models.DateTimeField(auto_now_add=True)),
                ('dequeued_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_wait_ms', models.IntegerField(default=0)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_queue', to='tasks.task')),
            ],
            options={
                'ordering': ['priority', 'queue_position'],
                'indexes': [models.Index(fields=['priority', 'queue_position'], name='dispatch_di_priorit_739195_idx'), models.Index(fields=['enqueued_at'], name='dispatch_di_enqueue_2f7549_idx')],
            },
        ),
    ]
