# Generated by Django 6.0.3 on 2026-04-19 21:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('agent_type', models.CharField(choices=[('ai', 'AI Agent'), ('human', 'Human Agent')], max_length=10)),
                ('capabilities', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
                ('api_endpoint', models.URLField(blank=True, null=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('api_key_encrypted', models.BinaryField(blank=True, null=True)),
                ('trust_score', models.FloatField(default=0.5)),
                ('success_rate', models.FloatField(default=0.5)),
                ('total_tasks', models.IntegerField(default=0)),
                ('total_earned', models.BigIntegerField(default=0)),
                ('avg_response_ms', models.IntegerField(default=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('rate_limit_per_minute', models.IntegerField(default=60)),
                ('rate_limit_remaining', models.IntegerField(default=60)),
                ('hourly_rate_sats', models.BigIntegerField(default=10000)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentHeartbeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='online', max_length=50)),
                ('latency_ms', models.IntegerField()),
                ('metrics', models.JSONField(default=dict)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='agents.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_ai_capable', models.BooleanField(default=True)),
                ('is_human_capable', models.BooleanField(default=True)),
                ('agents', models.ManyToManyField(blank=True, related_name='capability_set', to='agents.agent')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
