"""
Django settings for global_work_marketplace project.

Generated by 'django-admin startproject' using Django 5.0.3.
For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Session settings
SESSION_COOKIE_AGE = 86400  # 24 hours in seconds
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Login URLs - Add these lines
LOGIN_URL = '/django-admin/login/'
LOGIN_REDIRECT_URL = '/super-admin/'
LOGOUT_REDIRECT_URL = '/django-admin/login/'
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-!htw56rs)q(s%_w6_x5e73ax+#w0#rofl6&9f10)h)vwh@gab+')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

#ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']
#ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")
ALLOWED_HOSTS = [
    "global-work-marketplace.onrender.com",
    "127.0.0.1",
    "localhost",
]

# Application definition

INSTALLED_APPS = [
    # Django built-in apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',  # <-- ADDED THIS for ArrayField support
    
    # Third party apps
    'django_filters',
    'rest_framework',
    'corsheaders',
    'channels',
    
    # Your custom apps
    'apps.common.apps.CommonConfig',
    'apps.accounts.apps.AccountsConfig',
    'apps.agents.apps.AgentsConfig',
    'apps.analytics.apps.AnalyticsConfig',
    'apps.core_engine.apps.CoreEngineConfig',
    'apps.dispatch.apps.DispatchConfig',
    'apps.execution.apps.ExecutionConfig',
    'apps.payments.apps.PaymentsConfig',
    'apps.support.apps.SupportConfig',
    'apps.tasks.apps.TasksConfig',
    'apps.verification.apps.VerificationConfig',
    'apps.webhooks.apps.WebhooksConfig',
    'apps.super_admin.apps.SuperAdminConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#ROOT_URLCONF = 'config.urls'
ROOT_URLCONF = 'global_work_marketplace.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            BASE_DIR / 'apps/super_admin/templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'global_work_marketplace.wsgi.application'
ASGI_APPLICATION = "global_work_marketplace.asgi.application"

# Database - Using SQLite (Simple, no PostgreSQL needed)
# Note: SQLite doesn't support ArrayField. For production, switch to PostgreSQL.
# For development with SQLite, ArrayFields will be treated as JSONField.
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
#STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = True  # For development only
CORS_ALLOW_CREDENTIALS = True

# Channel Layers (for WebSockets)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',  # Use Redis in production
    },
}

# Cache Settings (Using local memory cache for simplicity)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Celery Settings (Optional - for background tasks)
CELERY_BROKER_URL = 'memory://'  # Simple in-memory broker for development
CELERY_RESULT_BACKEND = 'cache'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Email Settings (Console backend for development)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/debug.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'apps': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
if not LOGS_DIR.exists():
    LOGS_DIR.mkdir()

# Marketplace Specific Settings

# Agent Settings
AGENT_HEARTBEAT_TIMEOUT = 300  # 5 minutes
AGENT_MAX_CONCURRENT_TASKS = 5
AGENT_MIN_TRUST_SCORE = 0.3

# Task Settings
TASK_DEFAULT_TIMEOUT = 3600  # 1 hour
TASK_MAX_BUDGET_SATS = 100000000  # 100 million sats max
TASK_MIN_BUDGET_SATS = 1  # Minimum 1 sat

# Payment Settings
PLATFORM_FEE_PERCENT = 2.5  # 2.5% platform fee
MIN_DEPOSIT_SATS = 1000
ESCROW_TIMEOUT_HOURS = 48

# Security Settings
MAX_LOGIN_ATTEMPTS = 5
SESSION_TIMEOUT_MINUTES = 60
REQUIRE_EMAIL_VERIFICATION = False  # Set to True in production

# Rate Limiting
RATELIMIT_ENABLED = True
RATELIMIT_REQUESTS_PER_MINUTE = 60

# Webhook Settings
WEBHOOK_RETRY_ATTEMPTS = 3
WEBHOOK_RETRY_DELAY_SECONDS = 5

# Super Admin Settings
SUPER_ADMIN_EMAIL = os.environ.get('SUPER_ADMIN_EMAIL', 'admin@example.com')
SUPER_ADMIN_PASSWORD = os.environ.get('SUPER_ADMIN_PASSWORD', 'admin123')

# Feature Flags
ENABLE_AI_AGENTS = True
ENABLE_HUMAN_AGENTS = True
ENABLE_BATCH_TASKS = True
ENABLE_STREAMING_EXECUTION = True

# OpenAI Settings (for AI agents)
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')
OPENAI_MODEL = 'gpt-4-turbo-preview'

# Lightning Network Settings (for Bitcoin payments)
LIGHTNING_ENABLED = False  # Set to True when ready
LIGHTNING_RPC_HOST = os.environ.get('LIGHTNING_RPC_HOST', 'localhost:10009')
LIGHTNING_MACAROON_PATH = os.environ.get('LIGHTNING_MACAROON_PATH', '')
LIGHTNING_TLS_PATH = os.environ.get('LIGHTNING_TLS_PATH', '')

# Super Admin Dashboard Settings
SUPER_ADMIN_DASHBOARD_REFRESH_SECONDS = 30
SUPER_ADMIN_SHOW_SENSITIVE_DATA = True

# Audit Logging
ENABLE_AUDIT_LOGS = True
AUDIT_LOG_RETENTION_DAYS = 90